import angular from 'angular';

// Import app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';

import 'angular-ui-router';

import 'angular-animate';
import 'angular-aria';
import 'angular-messages';
import 'angular-material';

// Import templates file (generated by Gulp)
import './config/app.templates';
// Import app functionaity
import './layout';
import './services';


// Create & bootstrap application
const requires = [
  // 3rd Party Libraries
  'ui.router',
  'ngMaterial',
  // 
  'templates',
  //
  'app.layout',
  'app.services'
];

// Mount on window for testing
window.app = angular.module('app', requires);

// Initialize App Constants
angular.module('app').constant('AppConstants', constants);
// Initialize App Config
angular.module('app').config(appConfig);
// Initialize App Component
import Layout from './layout/layout.component';
angular.module('app').component('layout', Layout);
